#!/bin/bash
erb config/database.yml.erb > config/database.yml
cat config/database.yml

bundle exec rake db:migrate RAILS_ENV=test
bundle exec rspec spec RAILS_ENV=test

bundle exec rake db:migrate
bundle exec rails server
